### ISSUE TITLE
& is breaking translations

### ISSUE THREAD

**Issue by K0-RR** [PolyMC/Translations#10]
Originally posted by in https://github.com/PolyMC/Translations/issues/7#issuecomment-1066740763

the `amp;` part is being added automatically by weblate every time I save.

![Screenshot from 2022-03-17 21-18-48](https://user-images.githubusercontent.com/43277609/158888766-2b9d075a-338a-436c-8554-06f143881117.png)
![Screenshot from 2022-03-17 21-05-57](https://user-images.githubusercontent.com/43277609/158888791-3a1802d9-c61b-479e-8786-78f888ededee.png)

**Comment by Scrumplex** [comment]
Apparently you need to translate it as is. So don't escape it using `&amp;`

See https://stackoverflow.com/questions/51172593/qt-designer-add-ampersand-in-text-automatically

Or https://stackoverflow.com/questions/16666060/qt-why-add-to-the-string/16666135#16666135

**Comment by Scrumplex** [comment]
@RDKRACZ I fixed the Weblate configuration. Now it won't complain about unescaped HTML anymore. Any occurrence of `&amp;` should be changed back to `&`, `&gt;` to `>` and `&lt;` to `<`

**Comment by K0-RR** [comment]
Edit. Seems like there is not so much markup to fix.

Ok, but can't this be done outside of weblate via awk/sed or any text editor that has a `find and replace` option? (That would also require a quick push to weblate to prevent merge conflicts).
Forcing every translator to do it manually for every occurrence is kinda bad (if can be avoided).

**Comment by K0-RR** [comment]
I think the switch to .ts files deleted some translations and a few were marked as "Needs editing" even tho the source didn't change but that was probably unavoidable.

**Comment by K0-RR** [comment]
Typo in the source:
https://hosted.weblate.org/translate/polymc/polymc/pl/?checksum=ba0b4f111ecc6920
https://hosted.weblate.org/translate/polymc/polymc/pl/?checksum=1bcfb2838dc40d0f
https://hosted.weblate.org/translate/polymc/polymc/pl/?checksum=a5e14d09b3d09397 missing question mark
