### ISSUE TITLE
Missing translation strings

### ISSUE THREAD

**Issue by K0-RR** [PolyMC/Translations#8]
Cannot find these on weblate: "Add .jar", "Download mods"
![Screenshot from 2022-03-14 14-26-23](https://user-images.githubusercontent.com/43277609/158181811-3bca13bd-5987-4ff7-a31d-43f5bb846beb.png)
https://hosted.weblate.org/translate/polymc/polymc/pl/?q=Add+.jar
https://hosted.weblate.org/translate/polymc/polymc/pl/?q=Download+mods

And both of these "Mods"
![Screenshot from 2022-03-14 14-26-06](https://user-images.githubusercontent.com/43277609/158181844-89eb563d-b0f7-4b11-893a-05ddeae4ed1b.png)

**Comment by Scrumplex** [comment]
They were added a few days ago: https://github.com/PolyMC/Translations/commit/8f65ab199ae9be92fa3ab8ec0b2a45625c297fee

Not sure how long it takes for Weblate to find them

**Comment by K0-RR** [comment]
Ah, ok.

Can this https://github.com/PolyMC/Translations/blob/8f65ab199ae9be92fa3ab8ec0b2a45625c297fee/template.pot#L155

be changed to "About PolyMC" or "About the app" / "About launcher"?
The reason I'm asking for this is just "About" is "O" [in Polish](https://hosted.weblate.org/translate/polymc/polymc/pl/?offset=1&q=about) which looks odd, instead "O programie"/"O PolyMC" could be used.

**Comment by K0-RR** [comment]
This inconsistency is killing me:
![Screenshot from 2022-03-14 22-15-21](https://user-images.githubusercontent.com/43277609/158262860-709337fe-0774-447b-abb6-eda0d9fa0731.png)
https://github.com/PolyMC/Translations/blob/8f65ab199ae9be92fa3ab8ec0b2a45625c297fee/template.pot#L2458

**Comment by K0-RR** [comment]
This still isn't updated on Weblate.

**Comment by Scrumplex** [comment]
Fixed now

**Comment by Scrumplex** [comment]
> Ah, ok.
> 
> Can this
> 
> https://github.com/PolyMC/Translations/blob/8f65ab199ae9be92fa3ab8ec0b2a45625c297fee/template.pot#L155
> 
> be changed to "About PolyMC" or "About the app" / "About launcher"? The reason I'm asking for this is just "About" is "O" [in Polish](https://hosted.weblate.org/translate/polymc/polymc/pl/?offset=1&q=about) which looks odd, instead "O programie"/"O PolyMC" could be used.

Not sure what to put there in the application. It's the title of the tab in the "About" dialog. Maybe you can just translate it as `O programie` to convey the context.
